// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "fc90aa83-2838-41cb-81c7-3ab25a4f9359";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMsgChange();
void onAnalogGasChange();
void onAnalogRainChange();
void onHumidityChange();

String msg;
CloudTemperatureSensor temperature;
int analog_gas;
int analog_rain;
CloudRelativeHumidity humidity;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(msg, READWRITE, ON_CHANGE, onMsgChange);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(analog_gas, READWRITE, ON_CHANGE, onAnalogGasChange);
  ArduinoCloud.addProperty(analog_rain, READWRITE, ON_CHANGE, onAnalogRainChange);
  ArduinoCloud.addProperty(humidity, READWRITE, ON_CHANGE, onHumidityChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
